// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwDwOIYCqCG7LObufEw097BzGzOUOCazA',
    appId: '1:442039896279:web:5f540df5e1c5f3e2b50892',
    messagingSenderId: '442039896279',
    projectId: 'abarrotes-e5b20',
    authDomain: 'abarrotes-e5b20.firebaseapp.com',
    storageBucket: 'abarrotes-e5b20.firebasestorage.app',
    measurementId: 'G-WGY92DYQBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjrKGitUH727hRseH2NB6dEnvjYfsGS0Y',
    appId: '1:442039896279:android:b752d80307982efab50892',
    messagingSenderId: '442039896279',
    projectId: 'abarrotes-e5b20',
    storageBucket: 'abarrotes-e5b20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ9W4t93CnP7YDsziyEF50tjDNvwQX1j0',
    appId: '1:442039896279:ios:2f273563dc8dd945b50892',
    messagingSenderId: '442039896279',
    projectId: 'abarrotes-e5b20',
    storageBucket: 'abarrotes-e5b20.firebasestorage.app',
    iosBundleId: 'com.example.abarrotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ9W4t93CnP7YDsziyEF50tjDNvwQX1j0',
    appId: '1:442039896279:ios:2f273563dc8dd945b50892',
    messagingSenderId: '442039896279',
    projectId: 'abarrotes-e5b20',
    storageBucket: 'abarrotes-e5b20.firebasestorage.app',
    iosBundleId: 'com.example.abarrotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwDwOIYCqCG7LObufEw097BzGzOUOCazA',
    appId: '1:442039896279:web:2b022b7ee980d4c7b50892',
    messagingSenderId: '442039896279',
    projectId: 'abarrotes-e5b20',
    authDomain: 'abarrotes-e5b20.firebaseapp.com',
    storageBucket: 'abarrotes-e5b20.firebasestorage.app',
    measurementId: 'G-5K2GXNZ82Q',
  );
}
